AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an Ubuntu EC2 instance with Docker in specified VPC.

Parameters:
  EnvironmentName:
    Type: String
    AllowedValues:
      - Testing
      - Staging
      - Production
    Description: The name of the environment to deploy the EC2 instance.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and outbound traffic
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: EC2BasicAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - cloudwatch:*
                Resource: "*"
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: InstanceRole
  
  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [UbuntuAMI, !Ref "AWS::Region", AMI]
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PublicSubnet1ID"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the apt package index and install packages to allow apt to use a repository over HTTPS
          apt-get update
          apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common

          # Add Docker’s official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

          # Set up the stable repository for Docker
          add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) \
           stable"

          # Update the apt package index, and install the latest version of Docker CE and containerd
          apt-get update
          apt-get install -y docker-ce docker-ce-cli containerd.io

          # Add the current user to the Docker group to run Docker commands without sudo
          usermod -aG docker ubuntu

          # Install Docker Compose
          # Check the latest release of Docker Compose on https://github.com/docker/compose/releases
          COMPOSE_VERSION='1.29.2'
          curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

Mappings:
  UbuntuAMI:
    us-east-1:
      AMI: ami-1234567890abcdef0
    eu-west-1:
      AMI: ami-abcdef1234567890
    # Add more regions and AMI IDs as needed

Outputs:
  InstanceId:
    Description: The Instance ID of the EC2 instance
    Value: !Ref UbuntuInstance
